services:
  server:
    container_name: "rust-dc-bot-dev"
    build:
      context: .
      dockerfile: "./Dockerfile.dev"
    # env_file:
    #   - .env.development.local
    # ports:
    #   - 8081:8081 
    volumes:
      - ./:/app
